Feature/ds 87 implement event listener consumer for notification service
Dwit-Tech/notification-service pull request #5
Opened 2023-06-27 06:05 UTC by M-Jhay

2023-07-10 08:31 UTC, giftedGeorge requested changes
Please check the comments for changes that may be relevant.

2023-07-10 08:31 UTC, giftedGeorge commented on src/DwitTech.NotificationService.Core/Events/EmailEventConsumer.cs
> +                var cancellationToken = CancellationTokenSource.CreateLinkedTokenSource(stoppingToken, _cancellationTokenSource.Token).Token;
stoppingToken sounds like an action. Can you name it something else?

2023-07-10 08:31 UTC, giftedGeorge commented on src/DwitTech.NotificationService.Core/Services/EmailConsumerService.cs
> +                _logger.LogError(ex, "Error occurred while consuming Kafka message");
Why is this exception considered an error, but the previous exception is considered an "information". We should maintain consistency.

2023-07-10 08:31 UTC, giftedGeorge commented on src/DwitTech.NotificationService.WebApi/Properties/launchSettings.json
> +        "ASPNETCORE_ENVIRONMENT": "Development"
I think you forgot to return this to local

2023-07-10 08:31 UTC, giftedGeorge commented on src/DwitTech.NotificationService.Core/Models/EmailSentEvent.cs
Looks like this class is never used. Please remove.

2023-07-10 08:31 UTC, giftedGeorge commented on tests/DwitTech.NotificationService.Core.Tests/Events/EmailEventConsumerTest.cs
Why's this file commented out?

2023-07-10 09:00 UTC, johnny2565 commented on tests/DwitTech.NotificationService.Core.Tests/Events/EmailEventConsumerTest.cs
Please, kindly remove the file if has no place anymore

2023-07-10 09:06 UTC, johnny2565 requested changes
Please fix the comments on the PR

2023-07-10 18:57 UTC, M-Jhay commented on src/DwitTech.NotificationService.Core/Events/EmailEventConsumer.cs
> +                var cancellationToken = CancellationTokenSource.CreateLinkedTokenSource(stoppingToken, _cancellationTokenSource.Token).Token;
> stoppingToken

StoppingToken is a compound noun not an action word(verb)

2023-07-10 19:03 UTC, M-Jhay commented on tests/DwitTech.NotificationService.Core.Tests/Events/EmailEventConsumerTest.cs
> Please, kindly remove the file if has no place anymore

This is outdated already.

2023-07-10 19:04 UTC, M-Jhay commented on tests/DwitTech.NotificationService.Core.Tests/Events/EmailEventConsumerTest.cs
> Why's this file commented out?

This is outdated already. I already took the file out

2023-07-10 19:47 UTC, M-Jhay commented on src/DwitTech.NotificationService.Core/Services/EmailConsumerService.cs
> +                _logger.LogError(ex, "Error occurred while consuming Kafka message");
> Why is this exception considered an error, but the previous exception is considered an "information". We should maintain consistency.

Resolved

2023-07-10 19:47 UTC, M-Jhay commented on src/DwitTech.NotificationService.WebApi/Properties/launchSettings.json
> +        "ASPNETCORE_ENVIRONMENT": "Development"
> Member

Resolved

2023-07-10 19:48 UTC, M-Jhay commented on src/DwitTech.NotificationService.Core/Models/EmailSentEvent.cs
> Looks like this class is never used. Please remove.

Resolved

2023-07-10 19:48 UTC, M-Jhay commented
> 

Resolved

2023-07-11 06:26 UTC, johnny2565 approved these changes
The PR looks good to me

2023-07-14 08:28 UTC, giftedGeorge approved these changes

2023-07-14 17:17 UTC, dabensymon approved these changes

2023-07-14 17:17 UTC, merged